# Generated by Django 5.2.9 on 2026-01-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_securefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
